title: "Longish Blog"
description: "Longish Blog Desc"
baseurl: ""
url: "https://akalongman.github.io"

paginate: 5
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
